services:
  service-mini-server:
    build: 
      context: ../part_5/
      dockerfile: ./Dockerfile
    container_name: mini-server
    stdin_open: true # docker run -i
    tty: true        # docker run -t


  service-proxy-nginx:
    image: nginx
    container_name: proxy-nginx
    ports:
      - 80:8080
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
